development:
  database: example_development
  adapter: postgresql
  username: joe
  password: secret
  host: localhost
  port: 5432

production:
  database: example_production
  adapter: postgresql
  username: joe
  password: secret
  host: localhost
  port: 5432

test:
  database: example_test
  adapter: postgresql
  username: joe
  password: secret
  host: localhost
  port: 5432
